
# **L'analyse biographique des durées** 

## Questions 

On dispose de données dites "longitudinales", et on cherche à appréhender l'occurence d'un évènement au sein d'une population.
Les problématiques se basent sur les questions suivantes:  
<br>

* Observe-t-on la survenue de l'évènement pour l'ensemble des individus?
* Quelle est la durée jusqu'à la survenue de l'évènement?
* Quels sont les facteurs qui favorisent la survenue de cet évènement? Facteurs fixes ou  facteurs pouvant apparaitre/changer au cours de la période d'observation: variables dynamiques (**TVC**: *Time Varying Covariate*)

## Terminologies 

| Français                     | Anglais                        | 
| ---------------------------- | ------------------------------ | 
| Analyse des durées           | Duration analysis              |
| Analyse de survie/séjour     | Survival analysis              |
| Analyse de fiabilité         | Failure time data analysis     |
| Analyse des transitions      | Event-history analysis         |

Pour ce support, le choix de son titre me pose toujours problème pour éviter qu'il soit trop à rallonge. 
Si j'avais à trancher, il devrait un peu s'éterniser sous l'appelation **Introduction à l'analyse biographique des durées en présence de données censurée (à droite^[ce qui est déjà bien suffisant])**.


## Exemples d'analyse 

* **Nuptialité, Mise en couple**: cohabiter, décohabiter, se marier, Rompre une union ...  

* **Logement**: Changement de statut (locataire <=> propriétaire), mobilité résidentielle/migration ...  

* **Emploi**: Trouver un 1er emploi,  changer d'emploi, entrée ou sortie du chômage ...  

* **Fécondité**: Avoir un premier enfant, avoir un nouvel enfant ...  

* **Mortalité**: Décéder après diagnostic, survivre après l'administration un traitement, rechute...  


## Elements nécessaire à l'analyse 

1. **Un processus temporel**
   - Une échelle de mesure ou métrique temprelle: minutes, heures, jours, mois, années....
   - Une origine **commune** définissant un évènement de départ ^[Attention, dans le cadre des données prospectives ou de suivi, cela ne peut pas être le moment de l'inclusion à la base données]: naissance, mariage si on analyse la séparation, ..... 
   - Une définition précise de l'évènement d'étude.  
   - Une durée entre le début et la fin de la période d'observation, si nécessaire avec la fin de la période d'exposition au risque. Cette durée doit être généralement calculée à l'aide des informations de datation. 

2. **Une population soumise au risque** de connaître l'évènement (**Risk Set**)

3. ***Des variables explicatives*** ou ***covariables***
   - Fixes: sexe/genre, génération, niveau de diplôme le plus élevé,......
   - Dynamiques (TVC: *Time varying covariates*): 
     - Mesurées à tout moment entre le début et la sortie de l'observation: statut matrimonial, taille du ménage, statut d'activité...
     - Pour les modèles,  à l'exception du semi-paramétrique de Cox, en présence de données censurée la durée ou une transformation de celle-ci est une variable dynamique qui est également introduite comme variable indépendante pour assurer le bon ajustement des données. L'introduction directe d'une fonction de la durée comme variable dépendante ne peut se faire qu'en absence d'observation censurée, en particulier à droite.



## Types d'analyses

[A faire]



