project:
  type: website
  output-dir: docs
  
website:
  title: "Analyse des durées"
  search: 
    location: sidebar
  page-navigation: true
  page-footer: 
    center: "Marc Thévenin - Ined-Sms - Octobre 2022" 
    background: dark

  navbar:
    collapse-below: lg
    left:
#      - text: "**ANALYSE DES DUREES 2022**"
#       href: index.qmd
      - icon: github
        href: https://github.com/mthevenin/analyse_duree
      - icon: envelope
        href: mailto:marc.thevenin@ined.fr          

  sidebar:
      title: "PLAN"
      style: "docked"
      background: "info"
      collapse-level: 1
      contents:
        - section: "**Données et théorie**"
          contents:
          - introduction.qmd
          - Donnees.qmd
          - Theorie.qmd 
        - text: "---"      
        - section: "**Méthodes non paramétriques**"
          contents:
          - fsurvie.qmd
          - comp_fsurvie.qmd
        - text: "---"  
        - section: "**Modèles à risques proportionnels**"
          contents:
          - intro_mod.qmd
          - cox.qmd
          - discret.qmd
          - dynamiques.qmd
        - text: "---"  
        - section: "**Compléments**"
          contents:
          - parametrique.qmd
          - concurrent.qmd
          - frailty.qmd
        - text: "---"  
        - section: "**Programmation**"
          contents:
          - R.qmd
          - Stata.qmd
          - Sas.qmd
          - Python.qmd
        - text: "---"  
        - section: "**Annexes**"
          contents:
          - annexes.qmd

format:
  html:
    theme: 
      light: yeti
#      dark:  [yeti, theme-dark.scss]    
    css: style.css
    highlight-style: zenburn
#    code-block-bg: true
#    code-block-border-left: "#31BAE9"
    code-background: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-title: Sections
    code-tools:
      source: true


