---
title: "Fragilité et immunité"
---

---
title: "Fragilité et immunité"
---

**Je suis vraiment très très en retard dans la mise à jour de la formation**    
A faire un jour….mais le plus rapidement sera le mieux.  
Quelques remarques tout de même...

<br>

# Fragilité (Frailty)
Pour la fragilité (« frailty »), lire la dernière section du document de travail de Simon Quantin, je n’ai pas vu de meilleure présentation du problème que la sienne. Très important, car une des sources de la non proportionnalité des risques se trouvent dans l’omission de variables. Ici on va être confronté une omission sur des traits non observables. Certaines de ces caractéristiques vont « accélérer » dès le début de la période d’exposition la survenue de l’évènement. L’introduction d’un facteur de fragilité se fait par l’introduction d’un effet aléatoire dans le modèle, de nature plus complexe, reposant sur des hypothèse fortes et rendant l’interprétation des modèles plus compliquée (on doit passer par des graphiques, le tableau de régression ne pouvant  présenter des résultats qu'en début d’exposition).    


# Immunité (Cure fraction)
Pour l’immunité qui est un cas particulier du précédent, il est étudié depuis les années 1950. On va questionner l’exposition au risque d’une partie des observations. Visuellement on peut commencer à s'interroger lorsque la courbe de séjour ne tend pas vers 0 mais présente une longue asymptote sur une valeur nettement supérieure à 0: $\lim_{t \to \infty}S(t)=a$. Cette problématique peut fortement affecter les modèles de durées avec des évènements récurrents (non présentés). Pour traiter cette question, les modèles peuvent être de type mixte (probabilité d'être immunisé associée à un modèle de durée) ou non mixte de type bayesien. Il n’y a pas de méthode unifiée à ce jour, et reste très dépendante du champ d’analyse.  
En démographie des analyses, méthodologiquement plutôt complexes, ont été réalisées dans le champ de la fécondité.

