---
Title:  "FORMATION INED 2022: ANALYSE DES DUREES"   
format:
  html:
    toc: false
filters:
   - nutshell
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, render = knitr::normal_print)
library(knitr)
library (shiny)
library (rsconnect)
library(haven)
library(pander)
library(memisc)
library(fontawesome)
```


::: {.callout-important}  


## Test Grambsch-Therneau: version simplifiée versus version exacte

Depuis la version 3 du pkg `survival` le test permettant d'étudier la validé de l'hypothèse de constance des risques suite à l'estimation d'un modèle de Cox, est celui  proposé dans l'article de P.Grambsch et T.Therneau.  
Jusqu'à cette version du pkg, une version simplifiée du test était implémenté. C'est également le cas actuellement dans les autres applications statistiques tels que Stata (`estat phtest`), Sas (`proc phreg`), Python (`lifelines`,`statmodels`). 

Dans son principe le test (du score) n'est pas compliqué puisqu'il consiste à introduire une intéraction entre une fonction de la durée et un rapport de risque.  

Différence entre le test simplifié et le test exact:   

- ***Test simplifié***: La variance des résidus est celle de l'estimateur du rapport de risque de la covariable. Le test se réduit à une régression linéaire (ordinaire), la standardisation des résidus se fait en leur appliquant la variance du paramètre estimé par le modèle . 
- ***Test exact***: pour chaque résidu on calcule leur variance exacte à partir de la dérivée de l'équation de score. Le test consiste alors à estimer pour chaque covariable une régression linéaire généralisée. On peut retrouver les détails (très) techniques de la méthode dans l'[Article de Grambsch-Therneau](https://www.jstor.org/stable/2337123#metadata_info_tab_contents). 
 
Pour les personnes qui utilisent **R**, le test "simplifié" a été supprimé du package, ce qui ne me semble pas du tout une bonne idée. Je donne néanmoins un moyen simple de le récupérer et de l'exécuter.  
Sur quelques applications (données réelles et simulations réalisées avec le pkg `coxed`), le choix de la version du test ne semble pas neutre à la métrique temporelle utilisée: continue ou discrète/groupée. Se pose également un problème assez critique de reproductibilité, les résultats variants donc maintenant d'une solution logicielle à une autre ( R versus Stata-Sas-Python), et entre les deux versions du package `survival`. Comme si le type de transformation/fonction de la durée appliquée au test, également débattu dans la littérature, ne suffisait pas.  
:::

::: {.callout-note icon=false}  
## Bibliographie (courte mais efficace)

- **Cours de Gilbert Colletaz (version 2016)**: [`r fa("link", fill = "steelblue")`](https://docplayer.fr/69359088-Modeles-de-survie-notes-de-cours-master-2-esa-voies-professionnelle-et-recherche-gilbert-colletaz.html) 
- **Document de travail Insee de Simon Quantin (2019)**: [`r fa("link", fill = "steelblue")`](https://www.insee.fr/fr/statistiques/3695681) [avec version 2 de la librarie *`survival`*]  
:::


::: {.callout-note icon=false}  
## Liens INED

* **Site de l'Ined**: <https://www.ined.fr>  
* **Site du Service Méthodes Statistiques**: <https://sms.site.ined.fr> 
* **Site des Rencontres de Statistique Appliquée**: <https://statapp.site.ined.fr>
* **Site du séminaire R à l'Usage des Sciences Sociales (RUSS)**: <https://russ.site.ined.fr> 
:::


::: {.callout-note icon=false}  
## Autres supports

* <https://github.com/mthevenin>
* **Visualisation des données avec Stata (2020-2022)**: [`r fa("link", fill = "steelblue")`](https://mthevenin.github.io/stata_fr/index.html)
* **Introduction à Stata (2018 - un peu ancienne - MAJ en cours)**: [`r fa("link", fill = "steelblue")`](https://mthevenin.github.io/stata_programmation/formation/chapitre0.html)
* **Introduction à la regression logistique (v1 2022)**: [`r fa("link", fill = "steelblue")`](https://github.com/mthevenin/intro_logit/blob/main/modele_logit_v1_revise.pdf) 
:::


<br>
`r fa("address-card")` <mailto:marc.thevenin@ined.fr> - Service Méthodes Statistiques - Ined -  
<br>
`r fa("r-project")` Support réalisé avec [Rstudio](href:https://www.rstudio.com) - [Quarto](https://quarto.org/)  
`r fa("code")` Langages utilisés pour la partie programmation: [R](https://www.r-project.org/) - [Stata](https://www.stata.com/) - [Sas](https://www.sas.com/fr_fr/home.html) - [Python](https://www.python.org/) 

